require 'rps'

describe RPS do 
  subject(:game) { described_class.new("rock", opponent.generate_choice) }
  let(:opponent) { double :opponent, generate_choice: "paper" }

  it 'knows the choice the user made' do
    expect(subject.player).to eq "rock"
  end

  it 'knows the choice generated by the computer' do
    expect(subject.opponent).to eq "paper"
  end

  it 'can tell if the user won or not' do
    expect(subject.result).to eq "lose"
  end

  it 'can tell if there is a draw' do
    draw_game = RPS.new("paper", opponent.generate_choice)
    expect(draw_game.result).to eq "draw"
  end
end
