require 'rps'

describe RPS do 
  subject(:game) { described_class.new("rock", opponent)}
  let(:opponent) { double :opponent, generate_choice: "paper" }

  it 'knows the choice the user made' do
    expect(subject.player).to eq "rock"
  end

  it 'knows the choice generated by the computer' do
    expect(subject.opponent).to eq "paper"
  end

end