require 'player'

describe Player do
  
  context 'A human player creates a player object with the given paramaters' do
    subject(:player) {described_class.new(player_name, player_choice)}
    let(:player_name) { 'JoJo' }
    let(:player_choice) { 'Rock' }

    describe '#name' do
      it 'returns the players name' do
        expect(player.name).to eq 'JoJo'
     end
   end
  
    describe '#choice' do
      it 'returns the players score' do
       expect(player.choice).to eq 'Rock'
     end
    end
  end

  context 'An AI player is generated by default' do
    subject(:default_player) {described_class.new}

    describe '#name' do
      it 'has the default value' do
        expect(default_player.name).to eq 'Computer'
      end
    end
  end
end